# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-04-29 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
            ],
        ),
    ]
